---
hostname: "station"
ip: "192.168.10.10"
memory: 2048
cpus: 1

forwarded_ports:
  http: 8000
  mysql: 33060
  postgresql: 54320

authorize: ~/.ssh/id_rsa.pub

keys:
  - ~/.ssh/id_rsa

known_hosts:
  - github.com

folders:
  - map: ./www
    to: /var/www
    type: nfs

sites:
  - map: station
    to: /var/www